# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jlynn_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='weight',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
